In [1]:
import torch

In [2]:
def activation(x):
    
    return(1/(1+torch.exp(-x)))

In [3]:
torch.manual_seed(7)

features=torch.randn((1,5))
features

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [4]:
weights=torch.randn_like(features)
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [5]:
bias=torch.randn((1,1))

In [8]:
output=activation(torch.sum(weights*features)+bias)
output

tensor([[0.1595]])

In [9]:
features.shape

torch.Size([1, 5])

In [10]:
weights=weights.reshape(5,1)
weights.shape

torch.Size([5, 1])

In [12]:
output=activation(torch.mm(features,weights)+bias)
output

tensor([[0.1595]])