In [1]:
import torch

In [2]:
def activation(x):
    
    return(1/(1+torch.exp(-x)))

In [3]:
torch.manual_seed(7)

features=torch.randn((1,5))
features

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [4]:
weights=torch.randn_like(features)
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [5]:
bias=torch.randn((1,1))

In [8]:
output=activation(torch.sum(weights*features)+bias)
output

tensor([[0.1595]])

In [9]:
features.shape

torch.Size([1, 5])

In [10]:
weights=weights.reshape(5,1)
weights.shape

torch.Size([5, 1])

In [12]:
output=activation(torch.mm(features,weights)+bias)
output

tensor([[0.1595]])

In [37]:
torch.manual_seed(7)
features=torch.randn((1,3))
n_input=features.shape[1]
n_hidden=2
n_output=1

w1=torch.randn(n_input,n_hidden)
w2=torch.randn(n_hidden,n_output)

b1=torch.randn((1,n_hidden))
b2=torch.randn((1,n_output))

In [38]:
w1.shape

torch.Size([3, 2])

In [39]:
w2.shape

torch.Size([2, 1])

In [40]:
features.shape

torch.Size([1, 3])

In [41]:
h=activation(torch.mm(features,w1)+b1)
output=activation(torch.mm(h,w2)+b2)

In [42]:
output

tensor([[0.3171]])

In [43]:
import numpy as np

In [44]:
a=np.random.rand(4,3)
a

array([[0.15215464, 0.74428463, 0.7452852 ],
       [0.32137858, 0.90095126, 0.94324662],
       [0.38725197, 0.60734386, 0.91439618],
       [0.10430497, 0.99733406, 0.79087822]])

In [45]:
b=torch.from_numpy(a)
b

tensor([[0.1522, 0.7443, 0.7453],
        [0.3214, 0.9010, 0.9432],
        [0.3873, 0.6073, 0.9144],
        [0.1043, 0.9973, 0.7909]], dtype=torch.float64)